=== hanchao-c/MCC-PLUGIN/src/main/resources/template/mybatis/generator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.xxxs.com.cn" xmlns="http://www.xxxs.com.cn"
	elementFormDefault="qualified">

	<xs:element name="generators">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
				<xs:element name="contextGenerator" type="contextGenerator" minOccurs="0" maxOccurs="1"/>
				<xs:element name="mybatisGenerator" type="mybatisGenerator" minOccurs="1" maxOccurs="1"/>
				<xs:element name="table" type="table" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="property">
		<xs:attribute name="name" type="stringtype" use="required" />
		<xs:attribute name="value" type="stringtype" use="required" />
	</xs:complexType>

	<xs:complexType name="mybatisGenerator">
		<xs:sequence>
			<xs:element name="jdbcConnection" type="jdbcConnection" />
			<xs:element name="model" type="model" minOccurs="0" maxOccurs="1"/>
			<xs:element name="mapper" type="mapper" minOccurs="0" maxOccurs="1"/>
			<xs:element name="mapping" type="mapping" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  default="true"/>
		<xs:attribute name="inUsing" type="booleanType" use="required" />
	</xs:complexType>
	
	<xs:complexType name="model">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
	</xs:complexType>
	
	<xs:complexType name="mapper">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
	</xs:complexType>
	
	<xs:complexType name="mapping">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
	</xs:complexType>
	
	<xs:complexType name="jdbcConnection">
		<xs:attribute name="url" type="stringtype" use="required" />
		<xs:attribute name="userName" type="stringtype" use="required" />
		<xs:attribute name="password" type="stringtype" use="required" />
	</xs:complexType>

	<xs:complexType name="contextGenerator">
		<xs:sequence>
			<xs:element name="controller" type="controller" minOccurs="0" maxOccurs="1"/>
			<xs:element name="service" type="service" minOccurs="0" maxOccurs="1"/>
			<xs:element name="serviceImpl" type="serviceImpl" minOccurs="0" maxOccurs="1"/>
			<xs:element name="repository" type="repository" minOccurs="0" maxOccurs="1"/>
			<xs:element name="repositoryImpl" type="repositoryImpl" minOccurs="0" maxOccurs="1"/>
			<xs:element name="mock" type="modelMock" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  default="true"/>
		<xs:attribute name="inUsing" type="booleanType" use="required" />
	</xs:complexType>
	
	<xs:simpleType name="stringtype">
		<xs:restriction base="xs:string" />
	</xs:simpleType>

	<xs:simpleType name="booleanType">
		<xs:restriction base="xs:boolean" />
	</xs:simpleType>

	<xs:complexType name="modelMock">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="Mock" />
	</xs:complexType>
	
	<xs:complexType name="controller">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="Controller" />
	</xs:complexType>
	
	<xs:complexType name="service">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="Service" />
	</xs:complexType>
	
	<xs:complexType name="serviceImpl">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="ServiceImpl" />
	</xs:complexType>

	<xs:complexType name="repository">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="Repository" />
	</xs:complexType>
	
	<xs:complexType name="repositoryImpl">
		<xs:attribute name="targetPackage" type="stringtype" use="optional" />
		<xs:attribute name="templatePath" type="stringtype" use="optional" />
		<xs:attribute name="overwrite" type="booleanType" use="optional"  />
		<xs:attribute name="suffix" type="stringtype" use="optional" default="RepositoryImpl" />
	</xs:complexType>
	
	<xs:complexType name="table">
		<xs:attribute name="tableName" type="stringtype" use="required" />
		<xs:attribute name="domainObjectName" type="stringtype" use="required"/>
	</xs:complexType>
	

</xs:schema>

=== hanchao-c/MCC-PLUGIN/src/main/resources/template/generator-config-specific.xml
<?xml version="1.0" encoding="UTF-8"?>
<generators xmlns="http://www.9fbank.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.9fbank.com 
	https://raw.githubusercontent.com/hanchao-c/MCC-PLUGIN/master/src/main/resources/template/generator.xsd">
	
	<property name="auth" value="auth_Alice"/>
	<property name="contextTargetPackage" value="com.jlbank.route"/>
	<property name="mybatisTargetPackage" value="${contextTargetPackage}.repository"/>
	
	<contextGenerator targetPackage="${contextTargetPackage}" overwrite="true" inUsing="false" >
		<mock suffix="Mock" targetPackage="${contextTargetPackage}.model" overwrite="false"/>
		<controller suffix="Controller" targetPackage="${contextTargetPackage}.web"/>	
		<service suffix="Service" targetPackage="${contextTargetPackage}.service"/>
		<serviceImpl suffix="ServiceImpl" targetPackage="${contextTargetPackage}.service.impl"/>
		<repository suffix="Repository" targetPackage="${contextTargetPackage}.repository"/>
		<repositoryImpl suffix="RepositoryImpl" targetPackage="${contextTargetPackage}.repository.impl"/>	
	</contextGenerator>
	
	<mybatisGenerator targetPackage="${mybatisTargetPackage}" overwrite="true" inUsing="true">
		<jdbcConnection url="jdbc:mysql://127.0.0.1:3306/plugin_ins" 
						password="root" 
						userName="root"/>
	</mybatisGenerator>
	
	<table domainObjectName="mcc_plugin_test" tableName="MccPlugin_test"/>
</generators>
