=== hanchao-c/MCC-PLUGIN/src/main/resources/generator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.xxxs.com.cn"
           xmlns="http://www.xxxs.com.cn"
           elementFormDefault="qualified">

    <xs:element name="generators">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="properties" type="properties" minOccurs="0" maxOccurs="1"/>
                <xs:element name="javaObjectGenerators" type="javaObjectGenerators" minOccurs="1" maxOccurs="1"/>
                <xs:element name="mybatisGenerateConfig" type="mybatisGenerateConfig" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="properties">
        <xs:sequence minOccurs="0">
            <xs:element name="property" type="property" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="property">
        <xs:attribute name="name" type="stringtype" use="required"/>
        <xs:attribute name="value" type="stringtype" use="required"/>
    </xs:complexType>

    <xs:complexType name="javaObjectGenerators">
        <xs:sequence>
            <xs:element name="javaObject" type="javaObject" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="javaObject">
        <xs:sequence>
            <xs:element name="name" type="stringtype"/>
            <xs:element name="prefix" type="stringtype"/>
            <xs:element name="targetPackage" type="stringtype"/>
            <xs:element name="targetProject" type="stringtype"/>
            <xs:element name="templatePath" type="stringtype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mybatisGenerateConfig">
        <xs:attribute name="path" type="stringtype"/>
    </xs:complexType>

    <xs:simpleType name="stringtype">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:simpleType name="booleanType">
        <xs:restriction base="xs:boolean"/>
    </xs:simpleType>


</xs:schema>

=== hanchao-c/MCC-PLUGIN/src/main/resources/generator-config-simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<generators xmlns="http://www.xxxs.com.cn"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="/generator.xsd">

    <properties>
        <property name="auth" value="hc"/>
        <property name="date" value="a"/>
    </properties>

    <javaObjectGenerators>
        <javaObject>
            <name>0</name>
            <prefix>1</prefix>
            <targetPackage>2</targetPackage>
            <targetProject>3</targetProject>
            <templatePath>4</templatePath>
        </javaObject>
        <javaObject>
            <name>5</name>
            <prefix>6</prefix>
            <targetPackage>7</targetPackage>
            <targetProject>8</targetProject>
            <templatePath>9</templatePath>
        </javaObject>
    </javaObjectGenerators>

    <mybatisGenerateConfig path="123"/>

</generators>

=== hanchao-c/MCC-PLUGIN/src/main/resources/generate-config-simple.xml
<?xml version="1.0" encoding="UTF-8"?>
<generators xmlns="http://www.xxxs.com.cn"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="/generator.xsd">

    <properties>
        <property name="auth" value="hc"/>
        <property name="date" value="a"/>
    </properties>

    <javaObjectGenerators>
        <javaObject>
            <name>controller</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.controller</targetPackage>
            <targetProject>../training-server/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>createParam</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.model.param</targetPackage>
            <targetProject>../training-model/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>updateParam</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.model.param</targetPackage>
            <targetProject>../training-model/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>result</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.model.result</targetPackage>
            <targetProject>../training-model/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>converter</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.model.converter</targetPackage>
            <targetProject>../training-model/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>service</name>
            <prefix>I</prefix>
            <targetPackage>cn.ccos.training.service</targetPackage>
            <targetProject>../training-service/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>serviceImpl</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.service.impl</targetPackage>
            <targetProject>../training-service/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>manager</name>
            <prefix>I</prefix>
            <targetPackage>cn.ccos.training.manager</targetPackage>
            <targetProject>../training-service/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>managerImpl</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.manager.impl</targetPackage>
            <targetProject>../training-service/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
        <javaObject>
            <name>DTO</name>
            <prefix></prefix>
            <targetPackage>cn.ccos.training.dao.dto</targetPackage>
            <targetProject>../training-dao/src/main/java</targetProject>
            <templatePath></templatePath>
        </javaObject>
    </javaObjectGenerators>

    <mybatisGenerateConfig path="generate-config.xml"/>

</generators>
